Repository Kim-Yeon-ho/react-simple-toasts, pull requests merged in 2023-06, with the labels that each got.

#13 add reverse type to ToastProps
  src/index.tsx
Labels: :bug: Bug, 노유신

#10 Workflow 내에 빌드테스트를 추가했습니다.
  .github/workflows/buildTest.yml
Labels: :sparkles: Feats, 김연호

#12 add test code
  __tests__/toast.test.tsx
Labels: :sparkles: Feats, 노유신

#15 Eslint 규칙을 추가하였습니다.
  example/.eslintrc.cjs
Labels: :sparkles: Feats, 김지훈
