Repository Kim-Yeon-ho/react-simple-toasts, pull requests merged in 2023-05, with the labels that each got.

#7 Feature/fix readme jiho
  README.md
Labels: :memo: documentation, 박지호

#3 add reverse option
  src/index.tsx
Labels: :sparkles: Feats, 김지훈, 노유신

#2 apply clickableProps to render
  src/index.tsx
Labels: :bug: Bug, 김지훈, 노유신

#9 DeleteSliceMethod
  src/index.tsx
Labels: 김연호, 박지호

#8 Time변수를 삭제합니다.
  src/index.tsx
Labels: :bug: Bug, 김연호, 박지호
